spring:
  profiles:
    active: local

---


spring:
  datasource:
    # url: jdbc:h2:mem:database;DATABASE_TO_LOWER=TRUE
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always

jwt:
  secret-key: gotjrgoeh2rjtdmsqufakfdldkslqslekgoehrgkwlaktpdydkwhaejrlfdjdigkskqhspdyrhldwkdglekdghkdtmfjq=
  expiration: 1800000

